"""empty message

Revision ID: 373c3b5c043e
Revises: d693d10f1a78
Create Date: 2026-09-17 11:50:34.715903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373c3b5c043e'
down_revision = 'd693d10f1a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
